using System;

namespace ImmersiveWindow.Interop.Enums;

public enum QueryDisplayConfigFlags : uint
{
    QDC_ALL_PATHS = 0x00000001,
    QDC_ONLY_ACTIVE_PATHS = 0x00000002,
    QDC_DATABASE_CURRENT = 0x00000004
}

[Flags]
public enum SetDisplayConfigFlags : uint
{
    SDC_TOPOLOGY_INTERNAL = 0x00000001,
    SDC_TOPOLOGY_CLONE = 0x00000002,
    SDC_TOPOLOGY_EXTEND = 0x00000004,
    SDC_TOPOLOGY_EXTERNAL = 0x00000008,
    SDC_TOPOLOGY_SUPPLIED = 0x00000010,
    SDC_USE_SUPPLIED_DISPLAY_CONFIG = 0x00000020,
    SDC_VALIDATE = 0x00000040,
    SDC_APPLY = 0x00000080,
    SDC_NO_OPTIMIZATION = 0x00000100,
    SDC_SAVE_TO_DATABASE = 0x00000200,
    SDC_ALLOW_CHANGES = 0x00000400,
    SDC_PATH_PERSIST_IF_ONLY_MODE_CHANGED = 0x00000800,
    SDC_FORCE_MODE_ENUMERATION = 0x00001000,
    SDC_ALLOW_PATH_ORDER_CHANGES = 0x00002000
}

public enum DisplayConfigDeviceInfoType : int
{
    DISPLAYCONFIG_DEVICE_INFO_GET_SOURCE_NAME = 1,
    DISPLAYCONFIG_DEVICE_INFO_GET_TARGET_NAME = 2,
    DISPLAYCONFIG_DEVICE_INFO_GET_TARGET_PREFERRED_MODE = 3,
    DISPLAYCONFIG_DEVICE_INFO_GET_ADAPTER_NAME = 4,
    DISPLAYCONFIG_DEVICE_INFO_SET_TARGET_PERSISTENCE = 5,
    DISPLAYCONFIG_DEVICE_INFO_GET_TARGET_BASE_TYPE = 6,
    DISPLAYCONFIG_DEVICE_INFO_GET_SUPPORT_VIRTUAL_RESOLUTION = 7,
    DISPLAYCONFIG_DEVICE_INFO_SET_SUPPORT_VIRTUAL_RESOLUTION = 8,
    DISPLAYCONFIG_DEVICE_INFO_GET_ADVANCED_COLOR_INFO = 9,
    DISPLAYCONFIG_DEVICE_INFO_SET_ADVANCED_COLOR_INFO = 10,
    DISPLAYCONFIG_DEVICE_INFO_GET_QUERY_MONITOR_CONFIG_SUPPORT = 11,
    DISPLAYCONFIG_DEVICE_INFO_GET_SDR_WHITE_LEVEL = 12
}

public enum DisplayConfigRotation : uint
{
    DISPLAYCONFIG_ROTATION_IDENTITY = 1,
    DISPLAYCONFIG_ROTATION_ROTATE90 = 2,
    DISPLAYCONFIG_ROTATION_ROTATE180 = 3,
    DISPLAYCONFIG_ROTATION_ROTATE270 = 4,
    DISPLAYCONFIG_ROTATION_FORCE_UINT32 = 0xFFFFFFFF
}

public enum DisplayConfigModeInfoType : uint
{
    DISPLAYCONFIG_MODE_INFO_TYPE_SOURCE = 1,
    DISPLAYCONFIG_MODE_INFO_TYPE_TARGET = 2,
    DISPLAYCONFIG_MODE_INFO_TYPE_DESKTOP_IMAGE = 3,
    DISPLAYCONFIG_MODE_INFO_TYPE_FORCE_UINT32 = 0xFFFFFFFF
}
